from .index import *
from .Election_views import *
from .Position_views import *
from .Candidate_views import *
from .Voter_views import *
from .Ballot_views import *
from .Vote_views import *
from .Results_view import *
from .Settings_view import *
