# Generated by Django 4.0.1 on 2023-07-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='voters',
            field=models.ManyToManyField(blank=True, to='voting.Voter'),
        ),
    ]
