# Generated by Django 4.2 on 2023-04-21 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="voter", name="election",),
    ]
