# Generated by Django 4.2 on 2023-04-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0002_remove_voter_election"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="vote", unique_together={("voter", "ballot")},
        ),
        migrations.AddField(
            model_name="vote",
            name="candidates",
            field=models.ManyToManyField(
                related_name="candidates", to="voting.candidate"
            ),
        ),
        migrations.RemoveField(model_name="vote", name="candidate",),
    ]
