# Generated by Django 4.2 on 2023-04-21 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0003_alter_vote_unique_together_vote_candidates_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="vote", unique_together=set(),),
        migrations.AddField(
            model_name="vote",
            name="Position",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="voting.position",
            ),
        ),
        migrations.AddField(
            model_name="vote",
            name="candidate",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="voting.candidate",
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="vote_value",
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name="vote", unique_together={("voter", "Position", "candidate")},
        ),
        migrations.RemoveField(model_name="vote", name="candidates",),
    ]
