# Generated by Django 4.0.1 on 2023-07-11 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_remove_voter_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='description',
        ),
    ]
