# Generated by Django 4.2 on 2023-05-02 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0006_settings_results"),
    ]

    operations = [
        migrations.RenameField(
            model_name="settings", old_name="key", new_name="language",
        ),
        migrations.RemoveField(model_name="settings", name="value",),
    ]
