# Generated by Django 4.2 on 2023-05-03 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0007_rename_key_settings_language_remove_settings_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="voter",
            name="settings",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="voting.settings",
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="language",
            field=models.CharField(default="EN", max_length=100),
        ),
    ]
