# Generated by Django 4.2 on 2023-05-03 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0008_voter_settings_alter_settings_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="settings",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="voting.settings",
            ),
        ),
    ]
