# Generated by Django 4.2 on 2023-05-03 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0009_alter_voter_settings"),
    ]

    operations = [
        migrations.RemoveField(model_name="voter", name="settings",),
    ]
